server:
  redirectFromPort: 8080
  ssl:
    key-store-type: PKCS12 # The format used for the keystore. It could be set to JKS in case it is a JKS file
    key-store: classpath:keystore/storeka.p12 # The path to the keystore containing the certificate
    key-store-password: storeka # The password used to generate the certificate
    key-alias: storeka # The alias mapped to the certificate
    port: 8443
    enabled: false

spring:
  application:
    name: STOREKA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  datasource:
    url: jdbc:postgresql://localhost:5432/storeka
    username: postgres
    password: admin

cors.allowed.origins: http://localhost:4200
security:
  enabled: true